language: minimal
before_install: sudo modprobe fuse
before_script: docker build -f scripts/builder.Dockerfile -t stonix-builder .
script: docker run --cap-add SYS_ADMIN --device /dev/fuse --security-opt apparmor:unconfined stonix-builder
